services:
  pft-sr:
    build:
      context: .
    image: cuda12.9.1-node22.20.0-python3.13.8:bookworm-slim-uv
    container_name: pft-sr
    tty: true
    ipc: host
    environment:
      - DISPLAY=${DISPLAY:-host.docker.internal:0}
      - QT_X11_NO_MITSHM=1
    volumes:
      - .:/root/pft-sr
      - /tmp/.X11-unix:/tmp/.X11-unix

  pft-sr-gpu:
    extends:
      service: pft-sr
    container_name: pft-sr-gpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    profiles:
      - gpu
